FROM node:12

WORKDIR /app

ENV NODE_ENV production

ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install --no-optional

COPY . ./

EXPOSE 5000

RUN npm run build

# Discourage tampering
ENTRYPOINT [ "npm", "run", "serve" ]
