version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  prod-build:
    docker:
      - image: uwbpparamedics/uw-blueprint-paramedics-react:0.0.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run:
          name: Install docker-compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Run Docker compose
          command: |
            set -x
            docker-compose -f docker-compose-prod.yaml up -d

  dev-build:
    docker:
      - image: uwbpparamedics/uw-blueprint-paramedics-react:0.0.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Install docker-compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Creating mock env file
          command: touch paramedics-react.env
      - run:
          name: Run Docker compose
          command: |
            set -x
            docker-compose -f docker-compose-dev.yaml up -d

  dev-lint:
    docker:
      - image: uwbpparamedics/uw-blueprint-paramedics-react:0.0.2
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Installing packages
          command: npm install
      - run:
          name: Lint
          command: npm run lint

workflows:
  version: 2
  build-and-lint:
    jobs:
      - prod-build
      - dev-build
      - dev-lint
