version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  prod-build:
    docker:
      - image: uwbpparamedics/uw-blueprint-paramedics-react:0.0.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run:
          name: Install docker-compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Run Docker compose
          command: |
            set -x
            docker-compose -f docker-compose-prod.yaml up -d

workflows:
  version: 2
  build-and-lint:
    jobs:
      - prod-build
